"""add users table and link books

Revision ID: 28fa99fe5ea0
Revises: 4f5c5262fd98
Create Date: 2026-01-22 00:34:13.071944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28fa99fe5ea0'
down_revision: Union[str, Sequence[str], None] = '4f5c5262fd98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('fk_books_user_id', 'books', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_user_id', 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
