"""create books table

Revision ID: 4f5c5262fd98
Revises: 
Create Date: 2026-01-22 00:29:53.308799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f5c5262fd98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author', sa.Text(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('translated', sa.Boolean(), nullable=True),
    sa.Column('book_link', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('number_of_copies', sa.Integer(), nullable=True),
    sa.Column('times_read', sa.Integer(), nullable=True),
    sa.Column('dnf', sa.Boolean(), nullable=True),
    sa.Column('annotated', sa.Boolean(), nullable=True),
    sa.Column('acquired', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('main_genre', sa.Text(), nullable=True),
    sa.Column('sub_genre', sa.Text(), nullable=True),
    sa.Column('nonfiction', sa.Boolean(), nullable=True),
    sa.Column('intended_audience', sa.Text(), nullable=True),
    sa.Column('diverse', sa.Boolean(), nullable=True),
    sa.Column('lgbtqi_rep', sa.Boolean(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('medium', sa.Text(), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('imprint', sa.Text(), nullable=True),
    sa.Column('publication_type', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('series', sa.Text(), nullable=True),
    sa.Column('series_number', sa.Integer(), nullable=True),
    sa.Column('collection', sa.Text(), nullable=True),
    sa.Column('year_added', sa.Integer(), nullable=True),
    sa.Column('year_read', sa.Integer(), nullable=True),
    sa.Column('month_read', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name=op.f('users_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('books')
    # ### end Alembic commands ###
